version: '2'
services:
  bookstack:
    image: solidnerd/bookstack:0.28.0
    environment:
      - DB_HOST=192.168.5.214:3306
      - DB_DATABASE=bookstack
      - DB_USERNAME=root
      - DB_PASSWORD=Admin123
    volumes:
      - ./uploads:/var/www/bookstack/public/uploads
      - ./storage-uploads:/var/www/bookstack/storage/uploads
    ports:
      - "8082:80"
    restart: always

