version: '3.3'
services:
  ghost:
    image: ghost:3.8.0
    restart: always
    ports:
      - 8080:2368
    volumes:
      - ./content:/var/lib/ghost/content
      - ./config.production.json:/var/lib/ghost/config.production.json
    environment:
      NODE_ENV: production
