apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: 4xx
  namespace: flagger
spec:
  provider:
    type: prometheus
    address: http://promethues:9090
  query: |
    sum(
        rate(
            istio_requests_total{
              reporter="destination",
              destination_workload_namespace="{{ namespace }}",
              destination_workload="{{ target }}",
              response_code=~"4.*"
            }[{{ interval }}]
        )
    )
    /
    sum(
        rate(
            istio_requests_total{
              reporter="destination",
              destination_workload_namespace="{{ namespace }}",
              destination_workload="{{ target }}"
            }[{{ interval }}]
        )
    ) * 100