apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: 5xx-error
  namespace: default
spec:
  provider:
    type: prometheus
    address: http://promethues:9090
  query: |
    sum(
        rate(
            istio_requests_total{
              reporter="destination",
              destination_workload_namespace="{{ namespace }}",
              destination_workload="{{ target }}",
              response_code=~"5.*"
            }[{{ interval }}]
        )
    )
    /
    sum(
        rate(
            istio_requests_total{
              reporter="destination",
              destination_workload_namespace="{{ namespace }}",
              destination_workload="{{ target }}"
            }[{{ interval }}]
        )
    ) * 100