version: "2"

services:
  server:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=127.0.0.1:13306
      - DB_NAME=gitea
      - DB_USER=root
      - DB_PASSWD=oYV@QGeCy4TPk9xqXoC8Ah*l
    restart: always
    volumes:
      - ./data:/data
    ports:
      - "4000:3000"
      - "222:22"
