version: '2'
services:
  vault:
    image: vault:1.3.1
    container_name: vault
    ports:
      - "8200:8200"
    restart: always
    volumes:
      - ./logs:/vault/logs
      - ./file:/vault/file
      - ./config:/vault/config
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json
