version: "3.3"
services:
  shadowsocks:
    image: shadowsocks/shadowsocks-libev:v3.3.4
    ports:
      - "8388:8388/tcp"
      - "8388:8388/udp"
    environment:
      - METHOD=aes-256-gcm
      - PASSWORD=xxx
    restart: always