version: '3.3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "Admin123"
    restart: always
    volumes:
      - "./db:/var/lib/mysql"
    ports:
      - "3306:3306"
