version: "3.3"
services:
  nginx:
    container_name: nginx
    image: nginx:1.17.9
    restart: always
    ports:
      - 8081:8081
      - 8082:8082
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
