apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dns
  namespace: weave
spec:
  rules:
  - host: scope.dev.wiqun.zone
    http:
      paths:
      - path: /
        backend:
          serviceName: weave-scope-app
          servicePort: 80