---
version: "2.1"
services:
  nextcloud:
    image: linuxserver/nextcloud:18.0.4-ls79
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./appdata:/config
      - ./data:/data
    ports:
      - 8090:443
    restart: unless-stopped